-- Public form key on tenants (T-114) — per-tenant secret embedded in the
-- tenant's deployed Vite site so visitors can POST /api/v1/forms/submit
-- without exposing the owner's Supabase session. Generated by T-106
-- provision-stream at tenant creation, injected as VITE_FORM_KEY env on the
-- buyer's Vercel project.
--
-- Replaces the parent jsonpages-platform `tenants.api_key` (multi-purpose
-- key for MCP + forms + admin); save2repo splits those: MCP credentials live
-- in `tenant_agent_credentials` (T-110), admin auth via Supabase session,
-- public form submissions via this column.

alter table public.tenants
  add column if not exists public_form_key text;

create unique index if not exists tenants_public_form_key_unique_idx
  on public.tenants(public_form_key)
  where public_form_key is not null;
